import type { PortfolioContent } from './types'

const verifiedAt = '2026-07-23'

export const ptBR: PortfolioContent = {
  locale: 'pt-BR',
  seo: {
    title: 'Gabriel Gomes — Engenheiro de Produto Full-Stack',
    description:
      'Produtos digitais que entram em operação. Cases reais de SaaS, interfaces complexas, billing, automação e engenharia de produto.',
  },
  nav: {
    work: 'Trabalho',
    systems: 'Sistemas',
    process: 'Processo',
    about: 'Sobre',
    contact: 'Contato',
    projectCta: 'Conversar sobre um projeto',
    menu: 'Abrir menu',
    close: 'Fechar menu',
    language: 'Alterar idioma',
  },
  common: {
    home: 'Início',
    exploreCase: 'Explorar o case',
    visitProduct: 'Visitar produto',
    nextCase: 'Próximo case',
    verified: 'Dados verificados em julho de 2026',
    skip: 'Pular para o conteúdo',
    backToWork: 'Voltar aos trabalhos',
    currentLocale: 'Português',
  },
  home: {
    status: 'Disponível para projetos selecionados · São Paulo / remoto',
    eyebrow: 'Engenharia de produto · SaaS · sistemas em produção',
    titleTop: 'Produtos digitais que',
    titleAccent: 'entram em operação.',
    description:
      'Eu transformo processos complexos em produtos claros, confiáveis e comercialmente viáveis — da interface ao banco, da cobrança ao deploy.',
    primaryCta: 'Quero construir um produto',
    secondaryCta: 'Explorar os cases',
    metrics: [
      { value: '2', label: 'SaaS em produção', detail: 'ABAplay + LuminiPsi', verifiedAt, source: 'repositórios', public: true },
      { value: '300+', label: 'pacientes acompanhados', detail: 'no ABAplay', verifiedAt, source: 'produção ABAplay', public: true },
      { value: '4', label: 'clínicas pagantes', detail: 'receita recorrente real', verifiedAt, source: 'produção ABAplay', public: true },
      { value: '9 anos', label: 'liderando operações', detail: 'antes da engenharia', verifiedAt, source: 'trajetória', public: true },
    ],
    workEyebrow: 'Trabalhos selecionados',
    workTitle: 'Não são conceitos. São produtos que precisam funcionar.',
    workIntro:
      'Cada case mostra uma prova diferente: mercado, evolução técnica e a engenharia invisível que mantém o negócio operando.',
    systemEyebrow: 'Sistema em destaque',
    systemTitle: 'Uma infraestrutura financeira. Dois produtos. Zero cruzamento de dados.',
    systemText:
      'Assinaturas, webhooks idempotentes, proração, inadimplência e NFS-e automática compartilhando uma conta Asaas com isolamento por aplicação.',
    systemCta: 'Abrir a casa de máquinas',
    capabilitiesEyebrow: 'Capacidades',
    capabilitiesTitle: 'Da hipótese à operação, sem perder o fio do negócio.',
    capabilities: [
      {
        number: '01',
        title: 'Produto do zero',
        text: 'Descoberta, modelagem, protótipo e uma primeira versão que resolve o problema certo.',
        tags: ['Discovery', 'Arquitetura', 'UX'],
      },
      {
        number: '02',
        title: 'Frontend de produto',
        text: 'Fluxos complexos transformados em interfaces responsivas, acessíveis e fáceis de operar.',
        tags: ['React', 'Design systems', 'Motion'],
      },
      {
        number: '03',
        title: 'SaaS e integrações',
        text: 'Multi-tenancy, autenticação, permissões, billing, APIs, webhooks e automações resilientes.',
        tags: ['Node.js', 'PostgreSQL', 'Asaas'],
      },
      {
        number: '04',
        title: 'Operação real',
        text: 'Deploy, migrations, monitoramento, rollback, incidentes e suporte a quem paga.',
        tags: ['Docker', 'CI/CD', 'VPS'],
      },
    ],
    processEyebrow: 'Como eu trabalho',
    processTitle: 'Engenharia com contexto, decisão e responsabilidade.',
    processIntro:
      'IA acelera a execução. Arquitetura, julgamento e responsabilidade continuam humanos.',
    process: [
      { number: '01', title: 'Entender', text: 'Mapeio operação, restrições e quem paga pela solução.', artifact: 'Mapa do problema' },
      { number: '02', title: 'Modelar', text: 'Defino dados, papéis, fluxos críticos e critérios de sucesso.', artifact: 'Arquitetura + fluxos' },
      { number: '03', title: 'Prototipar', text: 'Transformo risco abstrato em interface que pode ser discutida.', artifact: 'Protótipo navegável' },
      { number: '04', title: 'Construir', text: 'Entrego em fatias verificáveis, com teste e documentação.', artifact: 'Produto funcional' },
      { number: '05', title: 'Operar', text: 'Coloco no ar, observo, respondo e aprendo com uso real.', artifact: 'Métricas + evolução' },
    ],
    aboutEyebrow: 'A pessoa por trás do sistema',
    aboutTitle: 'Cheguei ao código com uma década de empresa nas costas.',
    aboutText:
      'Antes de escrever software, passei nove anos liderando orçamento, equipes, fornecedores e processos. Hoje uso essa visão para construir tecnologia que serve à operação — não o contrário.',
    aboutCta: 'Conhecer minha trajetória',
    automationEyebrow: 'Aquisição como engenharia',
    automationTitle: 'Produto não se vende sozinho. Então eu construí a máquina de vendas também.',
    automationIntro:
      'Quando o ABAplay ficou pronto, tratei a aquisição B2B como outro sistema de produto: descobrir o mercado, qualificar oportunidades e conduzir conversas com contexto.',
    automationConclusion:
      'As clínicas pagantes do ABAplay entraram por esse funil. A automação não é um experimento isolado: ela fecha o ciclo entre produto, mercado e receita.',
    automations: [
      {
        stage: 'Descobrir',
        tool: 'Lead Finder',
        text: 'Mapeia clínicas no Google Maps com Playwright e classifica os resultados com um modelo local via Ollama, estado por estado e sem custo de API de IA.',
        facts: ['Playwright', 'Ollama local', 'Streamlit'],
      },
      {
        stage: 'Qualificar',
        tool: 'OperadoraHunter',
        text: 'Cruza bases públicas da ANS e do CNES com enriquecimento de sites. Cada oportunidade recebe score de 0 a 100 e uma estratégia de abordagem.',
        facts: ['Dados ANS/CNES', 'Score 0–100', 'Python'],
      },
      {
        stage: 'Converter',
        tool: 'Outreach Automation',
        text: 'Orquestra WhatsApp oficial e e-mail em cadência, com agentes especializados para informar, qualificar, explorar necessidades, responder objeções e converter.',
        facts: ['Meta Cloud API', '5 agentes LLM', '178 testes'],
      },
    ],
  },
  contact: {
    eyebrow: 'Próximo projeto',
    title: 'Tem um produto para lançar ou um sistema que precisa amadurecer?',
    text: 'Posso ajudar a transformar uma operação complexa em um produto claro, do primeiro fluxo à produção.',
    projectCta: 'Conversar no WhatsApp',
    emailCta: 'Enviar um e-mail',
    resumeCta: 'Ver currículo',
    availability: 'São Paulo, SP · projetos remotos e oportunidades de produto',
    whatsappMessage: 'Olá Gabriel! Vi seu novo portfólio e gostaria de conversar sobre um projeto.',
  },
  about: {
    eyebrow: 'Sobre',
    title: 'Negócio primeiro. Tecnologia a serviço da operação.',
    intro:
      'Minha trajetória não começou em uma IDE. Começou gerindo pessoas, contratos, orçamento e problemas que não podiam esperar.',
    paragraphs: [
      'Durante nove anos como Diretor Administrativo, aprendi que uma boa decisão precisa sobreviver ao orçamento, ao prazo, às pessoas e ao mundo real.',
      'Quando migrei para engenharia de software, levei essa disciplina comigo. O ABAplay nasceu de uma dor observada em clínicas reais e virou um SaaS pago. O LuminiPsi veio depois, incorporando tudo que a primeira operação ensinou sobre arquitetura, segurança, produto e confiabilidade.',
      'Hoje trabalho no encontro entre interface, sistema e negócio. Gosto de problemas onde a camada visual é apenas o começo — e onde billing, permissões, dados, automação e operação também precisam fazer sentido.',
    ],
    principlesTitle: 'Princípios que guiam meu trabalho',
    principles: [
      { title: 'Evidência antes de opinião', text: 'Decisões precisam de contexto, hipótese e forma de verificação.' },
      { title: 'Operar é diferente de gerar', text: 'Código só vira produto quando suporta uso, mudança, falha e responsabilidade.' },
      { title: 'Complexidade deve ser absorvida', text: 'O sistema pode ser sofisticado. A experiência do usuário não precisa parecer complicada.' },
      { title: 'Saber onde não usar IA', text: 'Automação responsável também exige reconhecer limites éticos, legais e humanos.' },
    ],
    timelineTitle: 'Trajetória',
    timeline: [
      { period: '2015 — 2024', role: 'Diretor Administrativo', org: 'Hope Construtora', text: 'Operações, orçamento, equipes, fornecedores e planejamento.' },
      { period: '2023 — hoje', role: 'Fundador & Engenheiro de Produto', org: 'ABAplay', text: 'Produto, código, infraestrutura, vendas e suporte de um SaaS em produção.' },
      { period: '2024', role: 'Prompt Engineer', org: 'Alignerr · Outlier', text: 'Avaliação de LLMs, edge cases e qualidade de resposta.' },
      { period: '2026 — hoje', role: 'Fundador & Engenheiro de Produto', org: 'LuminiPsi', text: 'Segundo SaaS, em produção, com TypeScript, testes e compliance no centro.' },
      { period: 'Em andamento', role: 'Engenharia de Software', org: 'Universidade Cruzeiro do Sul', text: 'Formação acadêmica acompanhando uma prática já orientada por produto.' },
    ],
  },
  resume: {
    eyebrow: 'Currículo',
    title: 'Engenheiro de Produto Full-Stack',
    intro: 'SaaS, interfaces complexas, integrações, automação e operação de produtos reais.',
    print: 'Imprimir / salvar PDF',
    download: 'Baixar PDF',
    summaryTitle: 'Resumo',
    summary:
      'Construo, lanço e opero produtos SaaS de ponta a ponta. Criador do ABAplay, plataforma multi-tenant com clientes pagantes e mais de 300 pacientes, e do LuminiPsi, SaaS em produção com conformidade CFP/LGPD. Background de nove anos em gestão administrativa.',
    experienceTitle: 'Experiência',
    skillsTitle: 'Competências',
    educationTitle: 'Formação',
  },
  cases: {
    abaplay: {
      key: 'abaplay',
      slug: 'abaplay',
      number: '01',
      name: 'ABAplay',
      category: 'Healthtech · SaaS B2B',
      status: 'Em produção desde 2025',
      title: 'Da planilha à operação clínica conectada.',
      summary:
        'Uma plataforma para clínicas de terapia infantil registrarem sessões, acompanharem evolução e aproximarem equipe e família.',
      role: 'Produto, UX, frontend, backend, infraestrutura, vendas e suporte',
      period: '2023 — hoje',
      accent: '#7c3aed',
      link: 'https://abaplay.app.br/',
      linkLabel: 'Conhecer o ABAplay',
      metrics: [
        { value: '4', label: 'clínicas pagantes', verifiedAt, source: 'produção', public: true },
        { value: '300+', label: 'pacientes', verifiedAt, source: 'produção', public: true },
        { value: '24/7', label: 'operação', verifiedAt, source: 'infraestrutura', public: true },
        { value: 'Auto', label: 'cobrança + NFS-e', detail: 'via Asaas', verifiedAt, source: 'produção', public: true },
      ],
      stack: ['React', 'Node.js', 'PostgreSQL', 'Socket.IO', 'Cloudflare R2', 'OpenAI', 'Docker'],
      media: [
        { src: '/projects/abaplay/session-desktop.png', alt: 'Registro de uma sessão terapêutica no ABAplay em tela desktop', caption: 'Registro de sessão · níveis de prompting e tentativas', kind: 'desktop' },
        { src: '/projects/registro-sessao.webp', alt: 'Registro de sessão ABA em dispositivo móvel', caption: 'Fluxo mobile em campo', kind: 'mobile' },
        { src: '/projects/psicologia-graficos.webp', alt: 'Gráfico longitudinal de progresso clínico', caption: 'Progresso por programa', kind: 'mobile' },
        { src: '/projects/portal-pais.webp', alt: 'Portal dos responsáveis com comunicação e progresso', caption: 'Portal da família', kind: 'mobile' },
        { src: '/projects/abaplay/library.webp', alt: 'Biblioteca de programas clínicos organizada por disciplina', caption: 'Biblioteca clínica', kind: 'detail' },
        { src: '/projects/abaplay/pei.webp', alt: 'Gerador de plano terapêutico individualizado', caption: 'Plano terapêutico versionado', kind: 'detail' },
      ],
      chapters: [
        {
          eyebrow: 'O problema',
          title: 'O dado que deveria orientar a terapia estava espalhado.',
          body: 'Clínicas de terapia infantil registravam sessões em papel, planilhas e mensagens. Terapeutas gastavam tempo consolidando relatórios, gestores perdiam visão da operação e famílias não conseguiam acompanhar o progresso.',
        },
        {
          eyebrow: 'A resposta',
          title: 'Um produto que conecta sessão, agenda, equipe e família.',
          body: 'O ABAplay reúne registro de sessões, programas terapêuticos, agenda, recorrência, chat, rastreios, prontuário e documentos. O fluxo foi desenhado para funcionar no consultório, em tela pequena e sob pressão de tempo.',
          bullets: ['Níveis de prompting ABA e tentativa a tentativa', 'Agenda com recorrência e cobertura de ausência', 'Portal dos responsáveis e chat em tempo real', 'PTI com assinatura e versionamento imutável'],
        },
        {
          eyebrow: 'Engenharia',
          title: 'As fronteiras do cliente existem em cada query.',
          body: 'O produto é multi-tenant por clínica. Permissões, documentos, conversas, IA e relatórios respeitam a mesma fronteira. Uploads usam URLs pré-assinadas para o navegador enviar diretamente ao R2, reduzindo carga e superfície no servidor.',
          bullets: ['SQL parametrizado e migrations versionadas', 'R2 privado com acesso autenticado', 'Quatro agentes de IA com quotas e auditoria', 'Jobs para trials, sessões, billing e mestria'],
        },
        {
          eyebrow: 'Operação',
          title: 'Quando algo quebra, existe cliente esperando.',
          body: 'Colocar em produção mudou o critério de qualidade: deploy, backup, monitoramento, migração e suporte deixaram de ser detalhes técnicos. Cobranças e NFS-e agora são automatizadas por APIs e webhooks do Asaas, reduzindo custo operacional sem acoplar a agenda clínica ao gateway.',
        },
      ],
      closingTitle: 'A prova que importa: empresas pagam para usar.',
      closingText:
        'O ABAplay demonstra que consigo atravessar todo o ciclo — entender a dor, construir, vender, operar e continuar evoluindo depois que o produto encontra o mundo real.',
    },
    luminipsi: {
      key: 'luminipsi',
      slug: 'luminipsi',
      number: '02',
      name: 'LuminiPsi',
      category: 'Mental health · SaaS B2B',
      status: 'Em produção · fase de validação',
      title: 'Compliance clínico tratado como produto.',
      summary:
        'Gestão clínica para psicólogos com prontuário, agenda, evoluções, documentos, escalas e sigilo incorporados ao fluxo.',
      role: 'Produto, design de interface, frontend, backend e operação',
      period: '2026 — hoje',
      accent: '#08786e',
      link: 'https://luminipsi.com.br/',
      linkLabel: 'Conhecer o LuminiPsi',
      metrics: [
        { value: '41', label: 'modelos de domínio', verifiedAt, source: 'Prisma', public: true },
        { value: '8', label: 'papéis de acesso', verifiedAt, source: 'RBAC', public: true },
        { value: 'Auto', label: 'cobrança + NFS-e', detail: 'via Asaas', verifiedAt, source: 'produção', public: true },
        { value: 'CI/CD', label: 'com rollback', verifiedAt, source: 'produção', public: true },
      ],
      stack: ['TypeScript', 'React', 'Express', 'Prisma', 'PostgreSQL', 'Playwright', 'Docker'],
      media: [
        { src: '/projects/luminipsi/dashboard.webp', alt: 'Painel integrado do LuminiPsi em dispositivo móvel', caption: 'Visão integrada da clínica', kind: 'mobile' },
        { src: '/projects/luminipsi/calendar.webp', alt: 'Agenda clínica do LuminiPsi', caption: 'Agenda e recorrência', kind: 'mobile' },
        { src: '/projects/luminipsi/patients.webp', alt: 'Lista de pacientes no LuminiPsi', caption: 'Prontuários ativos', kind: 'mobile' },
        { src: '/projects/luminipsi/evolutions.webp', alt: 'Histórico de evoluções clínicas', caption: 'Evoluções estruturadas', kind: 'mobile' },
        { src: '/projects/luminipsi/risk.webp', alt: 'Análise determinística de risco clínico', caption: 'Risco por regras explícitas', kind: 'mobile' },
        { src: '/projects/luminipsi/documents.webp', alt: 'Documentos clínicos gerados no LuminiPsi', caption: 'Documentos auditáveis', kind: 'mobile' },
      ],
      chapters: [
        {
          eyebrow: 'O problema',
          title: 'Sigilo e conformidade não podem ser uma nota de rodapé.',
          body: 'Psicólogos precisam registrar, guardar, compartilhar e descartar dados clínicos sob regras profissionais e legais. Muitas ferramentas começam pela agenda e tentam encaixar segurança depois. O LuminiPsi inverte essa ordem.',
        },
        {
          eyebrow: 'Produto',
          title: 'A segurança aparece no momento em que ela importa.',
          body: 'Registros restritos usam um segundo PIN de curta duração. Ações sensíveis geram auditoria. Oito papéis e permissões granulares separam recepção, profissional, gestão, paciente e responsável sem transformar o uso diário em burocracia.',
          bullets: ['PIN com token de 15 minutos', 'AuditLog clínico separado do SuperAdminLog', 'R2 privado sempre intermediado pela API', 'Retenção e descarte configuráveis'],
        },
        {
          eyebrow: 'Julgamento',
          title: 'Saber onde não usar IA também é engenharia.',
          body: 'O produto chegou a ter uma assistente clínica. Ela foi removida. Conteúdo de psicologia exige um nível de sigilo e responsabilidade que não deveria ser terceirizado a um modelo externo. As automações clínicas são determinísticas, explicáveis e auditáveis.',
        },
        {
          eyebrow: 'Evolução',
          title: 'Cada fragilidade anterior virou uma decisão explícita.',
          body: 'TypeScript de ponta a ponta, Prisma, Zod, TanStack Query, testes unitários, integração e e2e, containers equivalentes a produção e CI/CD com smoke test e rollback automático. Billing e NFS-e usam a mesma conta Asaas com endpoint, token e banco isolados por produto.',
          bullets: ['Monorepo TypeScript', '41 modelos Prisma', 'Testes de tenant, RBAC e quotas', 'Cobrança e nota automatizadas com baixo custo operacional'],
        },
      ],
      closingTitle: 'Produção é o começo da validação, não o fim.',
      closingText:
        'O LuminiPsi está no ar e pronto para aprender com o uso real. O case mostra uma engenharia mais deliberada, sem transformar ausência de tração inicial em promessa.',
    },
    billing: {
      key: 'billing',
      slug: 'asaas-billing',
      number: '03',
      name: 'Asaas × 2',
      category: 'Billing infrastructure · NFS-e',
      status: 'Operando em ABAplay e LuminiPsi',
      title: 'Uma conta financeira. Dois produtos isolados.',
      summary:
        'A infraestrutura que cria assinaturas, processa eventos, recupera inadimplência e emite notas sem cruzar dados entre aplicações.',
      role: 'Arquitetura, integração, regras de negócio, resiliência e operação',
      period: '2026',
      accent: '#067455',
      metrics: [
        { value: '2', label: 'produtos isolados', verifiedAt, source: 'código', public: true },
        { value: '200', label: 'no-op para evento alheio', detail: 'sem retentativa destrutiva', verifiedAt, source: 'webhooks', public: true },
        { value: '1×', label: 'evento aplicado', detail: 'idempotência', verifiedAt, source: 'billing events', public: true },
        { value: 'Auto', label: 'cobrança + NFS-e', verifiedAt, source: 'produção', public: true },
      ],
      stack: ['Asaas API', 'Webhooks', 'PostgreSQL', 'Node.js', 'TypeScript', 'Resend', 'NFS-e'],
      media: [],
      chapters: [
        {
          eyebrow: 'Contexto',
          title: 'O gateway não conhece as regras do produto.',
          body: 'No ABAplay o preço depende de vagas. No LuminiPsi depende de plano, ciclo e add-ons. O Asaas recebe um valor final — cálculo, quota, proração e experiência continuam sendo responsabilidade da aplicação.',
        },
        {
          eyebrow: 'Isolamento',
          title: 'Compartilhar conta não significa compartilhar dados.',
          body: 'Cada produto possui token e endpoint próprios. O webhook resolve assinatura ou cliente apenas no seu banco. Se o objeto pertence ao outro produto, responde 200 e não faz nada — importante porque falhas consecutivas podem interromper a fila da conta inteira.',
        },
        {
          eyebrow: 'Resiliência',
          title: 'As falhas mais caras são silenciosas.',
          body: 'Idempotência evita duplicação. Health jobs verificam a chave e a fila. Alertas operacionais avisam quando nota, credencial ou sincronização falham. A contratação segue best-effort: billing não derruba a agenda e uma falha fiscal não apaga a assinatura.',
          bullets: ['Entrega at-least-once', 'Idempotência por event ID', 'Alertas de operação', 'Proração calculada pela aplicação'],
        },
        {
          eyebrow: 'Fiscal',
          title: 'A nota nasce depois que o pagamento existe.',
          body: 'A NFS-e é armada por assinatura e emitida após confirmação. Isso evita receita fiscal para uma cobrança que nunca foi paga. Eventos fiscais resolvem pelo cliente, guardam PDF/XML quando autorizados e alertam em caso de erro.',
        },
      ],
      closingTitle: 'A interface é só a camada visível.',
      closingText:
        'Este sistema demonstra a parte do produto que o usuário quase não vê, mas que decide custo, confiança, receita e capacidade de operar.',
    },
  },
}

export const en: PortfolioContent = {
  ...ptBR,
  locale: 'en',
  seo: {
    title: 'Gabriel Gomes — Full-Stack Product Engineer',
    description:
      'Digital products that reach production. Real-world case studies in SaaS, complex interfaces, billing, automation, and product engineering.',
  },
  nav: {
    work: 'Work',
    systems: 'Systems',
    process: 'Process',
    about: 'About',
    contact: 'Contact',
    projectCta: 'Discuss a project',
    menu: 'Open menu',
    close: 'Close menu',
    language: 'Change language',
  },
  common: {
    home: 'Home',
    exploreCase: 'Explore the case',
    visitProduct: 'Visit product',
    nextCase: 'Next case',
    verified: 'Data verified in July 2026',
    skip: 'Skip to content',
    backToWork: 'Back to work',
    currentLocale: 'English',
  },
  home: {
    ...ptBR.home,
    status: 'Available for selected projects · São Paulo / remote',
    eyebrow: 'Product engineering · SaaS · production systems',
    titleTop: 'Digital products that',
    titleAccent: 'make it to production.',
    description:
      'I turn complex operations into clear, reliable, commercially viable products — from interface to database, billing to deployment.',
    primaryCta: 'Build a product with me',
    secondaryCta: 'Explore the cases',
    metrics: [
      { value: '2', label: 'SaaS products live', detail: 'ABAplay + LuminiPsi', verifiedAt, source: 'repositories', public: true },
      { value: '300+', label: 'patients supported', detail: 'through ABAplay', verifiedAt, source: 'ABAplay production', public: true },
      { value: '4', label: 'paying clinics', detail: 'real recurring revenue', verifiedAt, source: 'ABAplay production', public: true },
      { value: '9 years', label: 'leading operations', detail: 'before engineering', verifiedAt, source: 'career', public: true },
    ],
    workEyebrow: 'Selected work',
    workTitle: 'Not concepts. Products that have to work.',
    workIntro:
      'Each case offers a different proof: market traction, engineering growth, and the invisible systems keeping a business running.',
    systemEyebrow: 'Featured system',
    systemTitle: 'One financial infrastructure. Two products. No data crossover.',
    systemText:
      'Subscriptions, idempotent webhooks, proration, delinquency recovery, and automated service invoices on a shared Asaas account with application-level isolation.',
    systemCta: 'Enter the engine room',
    capabilitiesEyebrow: 'Capabilities',
    capabilitiesTitle: 'From hypothesis to operation, without losing sight of the business.',
    capabilities: [
      { number: '01', title: 'Zero-to-one product', text: 'Discovery, modeling, prototyping, and a first release solving the right problem.', tags: ['Discovery', 'Architecture', 'UX'] },
      { number: '02', title: 'Product frontend', text: 'Complex workflows turned into responsive, accessible interfaces built for real operations.', tags: ['React', 'Design systems', 'Motion'] },
      { number: '03', title: 'SaaS & integrations', text: 'Multi-tenancy, authentication, permissions, billing, APIs, webhooks, and resilient automation.', tags: ['Node.js', 'PostgreSQL', 'Asaas'] },
      { number: '04', title: 'Real operations', text: 'Deployments, migrations, monitoring, rollback, incidents, and support for paying customers.', tags: ['Docker', 'CI/CD', 'VPS'] },
    ],
    processEyebrow: 'How I work',
    processTitle: 'Engineering with context, decisions, and accountability.',
    processIntro: 'AI accelerates execution. Architecture, judgment, and accountability remain human.',
    process: [
      { number: '01', title: 'Understand', text: 'Map the operation, constraints, and who pays for the solution.', artifact: 'Problem map' },
      { number: '02', title: 'Model', text: 'Define data, roles, critical flows, and success criteria.', artifact: 'Architecture + flows' },
      { number: '03', title: 'Prototype', text: 'Turn abstract risk into an interface people can discuss.', artifact: 'Interactive prototype' },
      { number: '04', title: 'Build', text: 'Ship in verifiable slices, with tests and documentation.', artifact: 'Working product' },
      { number: '05', title: 'Operate', text: 'Launch, observe, respond, and learn from real use.', artifact: 'Metrics + evolution' },
    ],
    aboutEyebrow: 'The person behind the system',
    aboutTitle: 'I came to code with a decade of business behind me.',
    aboutText:
      'Before writing software, I spent nine years leading budgets, teams, suppliers, and processes. I now use that perspective to build technology that serves operations — not the other way around.',
    aboutCta: 'Read my story',
    automationEyebrow: 'Acquisition as engineering',
    automationTitle: "A product doesn't sell itself. So I built the sales machine too.",
    automationIntro:
      'Once ABAplay was ready, I treated B2B acquisition as another product system: discover the market, qualify opportunities, and run contextual conversations.',
    automationConclusion:
      'ABAplay’s paying clinics came through this funnel. The automation is not an isolated experiment: it closes the loop between product, market, and revenue.',
    automations: [
      {
        stage: 'Discover',
        tool: 'Lead Finder',
        text: 'Maps clinics on Google Maps with Playwright and classifies results with a local model through Ollama, state by state and with no AI API cost.',
        facts: ['Playwright', 'Local Ollama', 'Streamlit'],
      },
      {
        stage: 'Qualify',
        tool: 'OperadoraHunter',
        text: 'Cross-references public ANS and CNES datasets with website enrichment. Every opportunity gets a 0–100 score and a recommended approach.',
        facts: ['ANS/CNES data', '0–100 score', 'Python'],
      },
      {
        stage: 'Convert',
        tool: 'Outreach Automation',
        text: 'Orchestrates official WhatsApp and email sequences with specialized agents for information, qualification, discovery, objection handling, and conversion.',
        facts: ['Meta Cloud API', '5 LLM agents', '178 tests'],
      },
    ],
  },
  contact: {
    eyebrow: 'Next project',
    title: 'Have a product to launch or a system that needs to grow up?',
    text: 'I can help turn a complex operation into a clear product, from the first workflow to production.',
    projectCta: 'Message me on WhatsApp',
    emailCta: 'Send an email',
    resumeCta: 'View résumé',
    availability: 'São Paulo, Brazil · remote projects and product opportunities',
    whatsappMessage: 'Hi Gabriel! I saw your new portfolio and would like to discuss a project.',
  },
  about: {
    eyebrow: 'About',
    title: 'Business first. Technology in service of operations.',
    intro:
      'My career did not start in an IDE. It started by managing people, contracts, budgets, and problems that could not wait.',
    paragraphs: [
      'During nine years as an Administrative Director, I learned that a good decision has to survive budgets, deadlines, people, and the real world.',
      'When I moved into software engineering, I brought that discipline with me. ABAplay started from a pain observed in real clinics and became a paid SaaS. LuminiPsi came next, incorporating everything the first operation taught me about architecture, security, product, and reliability.',
      'Today I work where interface, systems, and business meet. I enjoy problems where the visual layer is only the beginning — and where billing, permissions, data, automation, and operations must also make sense.',
    ],
    principlesTitle: 'Principles behind my work',
    principles: [
      { title: 'Evidence before opinion', text: 'Decisions need context, a hypothesis, and a way to verify them.' },
      { title: 'Operating is different from generating', text: 'Code becomes a product only when it supports use, change, failure, and accountability.' },
      { title: 'Complexity should be absorbed', text: 'The system may be sophisticated. The user experience should not feel complicated.' },
      { title: 'Knowing where not to use AI', text: 'Responsible automation also means recognizing ethical, legal, and human limits.' },
    ],
    timelineTitle: 'Journey',
    timeline: [
      { period: '2015 — 2024', role: 'Administrative Director', org: 'Hope Construtora', text: 'Operations, budgets, teams, suppliers, and planning.' },
      { period: '2023 — today', role: 'Founder & Product Engineer', org: 'ABAplay', text: 'Product, code, infrastructure, sales, and support for a live SaaS.' },
      { period: '2024', role: 'Prompt Engineer', org: 'Alignerr · Outlier', text: 'LLM evaluation, edge cases, and response quality.' },
      { period: '2026 — today', role: 'Founder & Product Engineer', org: 'LuminiPsi', text: 'A second live SaaS with TypeScript, testing, and compliance at its core.' },
      { period: 'In progress', role: 'Software Engineering', org: 'Universidade Cruzeiro do Sul', text: 'Academic study alongside product-oriented practice.' },
    ],
  },
  resume: {
    eyebrow: 'Résumé',
    title: 'Full-Stack Product Engineer',
    intro: 'SaaS, complex interfaces, integrations, automation, and real-world product operations.',
    print: 'Print / save PDF',
    download: 'Download PDF',
    summaryTitle: 'Summary',
    summary:
      'I build, launch, and operate SaaS products end to end. Creator of ABAplay, a multi-tenant platform with paying customers and 300+ patients, and LuminiPsi, a live SaaS centered on professional compliance and privacy. Nine-year background in administrative leadership.',
    experienceTitle: 'Experience',
    skillsTitle: 'Skills',
    educationTitle: 'Education',
  },
  cases: {
    abaplay: {
      ...ptBR.cases.abaplay,
      category: 'Healthtech · B2B SaaS',
      status: 'Live since 2025',
      title: 'From spreadsheets to a connected clinical operation.',
      summary:
        'A platform for pediatric therapy clinics to record sessions, track progress, and connect teams with families.',
      role: 'Product, UX, frontend, backend, infrastructure, sales, and support',
      period: '2023 — today',
      linkLabel: 'Visit ABAplay',
      metrics: [
        { value: '4', label: 'paying clinics', verifiedAt, source: 'production', public: true },
        { value: '300+', label: 'patients', verifiedAt, source: 'production', public: true },
        { value: '24/7', label: 'operation', verifiedAt, source: 'infrastructure', public: true },
        { value: 'Auto', label: 'billing + invoices', detail: 'via Asaas', verifiedAt, source: 'production', public: true },
      ],
      media: ptBR.cases.abaplay.media.map((item, index) => ({
        ...item,
        alt: ['Therapy session recording in ABAplay on desktop', 'Mobile ABA session recording', 'Longitudinal clinical progress chart', 'Family portal with communication and progress', 'Clinical program library organized by discipline', 'Individualized treatment plan generator'][index],
        caption: ['Session recording · prompts and trials', 'Mobile workflow in the field', 'Progress by program', 'Family portal', 'Clinical library', 'Versioned treatment plan'][index],
      })),
      chapters: [
        { eyebrow: 'The problem', title: 'The data meant to guide therapy was scattered.', body: 'Pediatric therapy clinics recorded sessions across paper, spreadsheets, and messages. Therapists spent hours consolidating reports, managers lost visibility, and families struggled to follow progress.' },
        { eyebrow: 'The response', title: 'A product connecting sessions, schedules, teams, and families.', body: 'ABAplay brings together session recording, treatment programs, scheduling, recurrence, chat, screenings, records, and documents. The workflow was designed for small screens and time-pressured clinical work.', bullets: ['ABA prompt levels and trial-by-trial recording', 'Recurring schedules and absence coverage', 'Family portal and real-time chat', 'Signed, immutable treatment plan versions'] },
        { eyebrow: 'Engineering', title: 'Customer boundaries exist in every query.', body: 'The product is multi-tenant by clinic. Permissions, documents, conversations, AI, and reports respect the same boundary. Presigned URLs let the browser upload directly to private R2 storage.', bullets: ['Parameterized SQL and versioned migrations', 'Private R2 with authenticated access', 'Four AI agents with quotas and audit trails', 'Jobs for trials, sessions, billing, and mastery'] },
        { eyebrow: 'Operations', title: 'When something breaks, a customer is waiting.', body: 'Production changed the quality bar: deployment, backups, monitoring, migrations, and support stopped being technical details. Billing and service invoices are now automated through Asaas APIs and webhooks, lowering operational cost without coupling clinical scheduling to the gateway.' },
      ],
      closingTitle: 'The proof that matters: companies pay to use it.',
      closingText: 'ABAplay shows I can cross the whole cycle — understand the pain, build, sell, operate, and keep evolving after the product meets the real world.',
    },
    luminipsi: {
      ...ptBR.cases.luminipsi,
      category: 'Mental health · B2B SaaS',
      status: 'Live · validation stage',
      title: 'Clinical compliance treated as product.',
      summary:
        'Clinical management for psychologists with records, schedules, notes, documents, assessments, and privacy built into the workflow.',
      role: 'Product, interface design, frontend, backend, and operations',
      period: '2026 — today',
      linkLabel: 'Visit LuminiPsi',
      metrics: [
        { value: '41', label: 'domain models', verifiedAt, source: 'Prisma', public: true },
        { value: '8', label: 'access roles', verifiedAt, source: 'RBAC', public: true },
        { value: 'Auto', label: 'billing + invoices', detail: 'via Asaas', verifiedAt, source: 'production', public: true },
        { value: 'CI/CD', label: 'with rollback', verifiedAt, source: 'production', public: true },
      ],
      media: ptBR.cases.luminipsi.media.map((item, index) => ({
        ...item,
        alt: ['LuminiPsi integrated dashboard on mobile', 'LuminiPsi clinical calendar', 'LuminiPsi patient list', 'Clinical note history', 'Deterministic clinical risk analysis', 'Auditable clinical documents'][index],
        caption: ['Integrated clinic view', 'Scheduling and recurrence', 'Active records', 'Structured clinical notes', 'Risk through explicit rules', 'Auditable documents'][index],
      })),
      chapters: [
        { eyebrow: 'The problem', title: 'Privacy and compliance cannot be an afterthought.', body: 'Psychologists must record, store, share, and dispose of clinical data under professional and legal rules. Many tools begin with scheduling and bolt security on later. LuminiPsi reverses that order.' },
        { eyebrow: 'Product', title: 'Security appears exactly when it matters.', body: 'Restricted records require a short-lived secondary PIN. Sensitive actions are audited. Eight roles and granular permissions separate reception, clinicians, management, patients, and guardians without turning daily work into bureaucracy.', bullets: ['PIN with a 15-minute token', 'Clinical AuditLog separated from SuperAdminLog', 'Private R2 mediated by authenticated APIs', 'Configurable retention and disposal'] },
        { eyebrow: 'Judgment', title: 'Knowing where not to use AI is engineering too.', body: 'The product once included a clinical assistant. I removed it. Psychology content demands confidentiality and accountability that should not be outsourced to an external model. Clinical automation is deterministic, explainable, and auditable.' },
        { eyebrow: 'Growth', title: 'Every earlier weakness became an explicit decision.', body: 'End-to-end TypeScript, Prisma, Zod, TanStack Query, unit, integration, and e2e tests, production-like containers, and CI/CD with smoke tests and automatic rollback. Billing and service invoices share the Asaas account while keeping each product’s token, endpoint, and database isolated.', bullets: ['TypeScript monorepo', '41 Prisma models', 'Tenant, RBAC, and quota tests', 'Low-overhead automated billing and service invoices'] },
      ],
      closingTitle: 'Production is the start of validation, not the finish line.',
      closingText: 'LuminiPsi is live and ready to learn from real use. The case shows more deliberate engineering without turning early-stage traction into a promise.',
    },
    billing: {
      ...ptBR.cases.billing,
      category: 'Billing infrastructure · Service invoices',
      status: 'Running across ABAplay and LuminiPsi',
      title: 'One financial account. Two isolated products.',
      summary:
        'Infrastructure that creates subscriptions, processes events, recovers delinquency, and issues invoices without crossing application data.',
      role: 'Architecture, integration, business rules, resilience, and operations',
      metrics: [
        { value: '2', label: 'isolated products', verifiedAt, source: 'code', public: true },
        { value: '200', label: 'no-op for foreign events', detail: 'no destructive retry', verifiedAt, source: 'webhooks', public: true },
        { value: '1×', label: 'event applied', detail: 'idempotency', verifiedAt, source: 'billing events', public: true },
        { value: 'Auto', label: 'billing + invoices', verifiedAt, source: 'production', public: true },
      ],
      chapters: [
        { eyebrow: 'Context', title: 'The gateway does not know the product rules.', body: 'ABAplay prices by seats. LuminiPsi uses plans, billing cycles, and add-ons. Asaas receives a final amount — calculation, quota, proration, and experience remain the application’s responsibility.' },
        { eyebrow: 'Isolation', title: 'Sharing an account does not mean sharing data.', body: 'Each product has its own token and endpoint. A webhook resolves the subscription or customer only in its database. If the object belongs to the other product, it returns 200 and does nothing — critical because consecutive failures can pause the entire account queue.' },
        { eyebrow: 'Resilience', title: 'The most expensive failures are silent.', body: 'Idempotency prevents duplication. Health jobs check API keys and queue state. Operational alerts report invoice, credential, and synchronization failures. Billing cannot take down the clinical schedule.', bullets: ['At-least-once delivery', 'Idempotency by event ID', 'Operational alerts', 'Application-owned proration'] },
        { eyebrow: 'Tax', title: 'The invoice is born after payment exists.', body: 'Service invoices are configured per subscription and issued after payment confirmation. Fiscal events resolve by customer, store PDF/XML when authorized, and alert on errors.' },
      ],
      closingTitle: 'The interface is only the visible layer.',
      closingText: 'This system demonstrates the part of product work users barely see — but which determines cost, trust, revenue, and operational capability.',
    },
  },
}

export const contentByLocale = {
  'pt-BR': ptBR,
  en,
} as const
